#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🔍 Performing some checks before commit'

# Check Prettier standards
npm run check-format ||
(
    echo 'Prettier Check Failed. Run npm run prettify and try commit again.';
    false;
)

# Check ESLint Standards
npm run lint ||
(
        echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false;
)

# Check tsconfig standards
npm run check-types ||
(
    echo 'Failed Type check. Make the changes required above.'
    false;
)

npm run build ||
(
    echo 'Next build failed: View the errors above to see why.'
    false;
)

# If everything passes... Now we can commit
echo '✅ All checks passed, committing now'